import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Home Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <header className="py-[50px] bg-blue-500 text-white">Header</header>
        <main className="py-[100px]">{children}</main>
        <footer className="py-[50px] bg-gray-100">footer</footer>
      </body>
    </html>
  );
}
